version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "assi"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-07944609363a76951","subnet-01e9bbe958bf2cbb0" ]
            SecurityGroups: ["sg-09be88a7c588fe4c9"]
            AssignPublicIp: "ENABLED"
