version: 0.2
env:
  variables:
    VERSION: "latest"
    IMAGE_REPO_NAME: "assignement1"
    AWS_ACCOUNT_ID: "097034695032"
    AWS_DEFAULT_REGION: "eu-west-1"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Entered the install phase...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region     $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $IMAGE_REPO_NAME:$VERSION ..
      - docker build -t $IMAGE_REPO_NAME:$VERSION .
      - printf '{"ImageURI":"%s"}'  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION  > /imageDetail.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image $IMAGE_REPO_NAME:$VERSION ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION
artifacts:
    files: /imageDetail.json
    discard-paths: yes